### ISSUE TITLE
Convert MSG to EML fails with error dialogs

### ISSUE THREAD

**Issue by bill-e-ghote** [microsoft/mfcmapi#610] opened 2023-08-22 12:29 UTC
At work, I have:
Microsoft® Outlook® for Microsoft 365 MSO (Version 2302 Build 16.0.16130.20690) 32-bit 

When I try to convert an MSG file to EML using the latest release 32-bit MFCMapi.exe, I get the following errors:

Error: IConverterSession not found. This interface is only supported by Outlook 2003 and higher.
Code: REGDB_E_CLASSNOTREG == 0x80040154
Function CoCreateInstance( guid::CLSID_IConverterSession, nullptr, CLSCTX_INPROC_SERVER, guid::IID_IConverterSession, reinterpret_cast<LPVOID*>(&lpConverter))
File D:\a\1\s\core\mapi\mapiMime.cpp
Line 92

Error: 
Code: REGDB_E_CLASSNOTREG == 0x80040154
Function ExportIMessageToEML(pMessage, lpszEMLFile, convertFlags, et, mst, ulWrapLines, lpAdrBook)
File D:\a\1\s\core\mapi\mapiMime.cpp
Line 205

Error: 
Code: REGDB_E_CLASSNOTREG == 0x80040154
Function mapi::mapimime::ConvertMSGToEML( msgfile.c_str(), emlfile.c_str(), ulConvertFlags, et, mst, ulWrapLines, lpAdrBook)
File D:\a\1\s\UI\Dialogs\ContentsTable\MainDlg.cpp
Line 1489

**Comment by MasterOizo** [comment] 2023-10-24 10:42
I got the same Issue for Office 365 Version 2309 Build 16827.20166
Browsing the Mailaccount works fine.

The error occurs when I Convert a .msg File to .eml or if I try to "Export message" as .eml.
`Error: IConverterSession not found. This interface is only supported by Outlook 2003 and higher.
Code: REGDB_E_CLASSNOTREG == 0x80040154
Function CoCreateInstance( guid::CLSID_IConverterSession, nullptr, CLSCTX_INPROC_SERVER, guid::IID_IConverterSession, reinterpret_cast<LPVOID*>(&lpConverter))
File D:\a\1\s\core\mapi\mapiMime.cpp
Line 92

Error: 
Code: REGDB_E_CLASSNOTREG == 0x80040154
Function mapi::mapimime::ExportIMessageToEML( lpMessage, filename.c_str(), ulConvertFlags, et, mst, ulWrapLines, bDoAdrBook ? lpAddrBook : nullptr)
File D:\a\1\s\UI\file\exporter.cpp
Line 135

Error: 
Code: REGDB_E_CLASSNOTREG == 0x80040154
Function exporter.exportMessage(lpMessage)
File D:\a\1\s\UI\Dialogs\ContentsTable\FolderDlg.cpp
Line 1357`


`Error: 
Code: MAPI_E_INTERFACE_NOT_SUPPORTED == 0x80004002
Function lpMessage->OpenProperty( PR_INTERNET_CONTENT, const_cast<LPIID>(&IID_IStream), 0, NULL, reinterpret_cast<LPUNKNOWN*>(&pStrmSrc))
File D:\a\1\s\core\mapi\mapiFile.cpp
Line 342

Error: 
Code: MAPI_E_INTERFACE_NOT_SUPPORTED == 0x80004002
Function file::SaveToEML(lpMessage, filename)
File D:\a\1\s\UI\file\exporter.cpp
Line 114

Error: 
Code: MAPI_E_INTERFACE_NOT_SUPPORTED == 0x80004002
Function exporter.exportMessage(lpMessage)
File D:\a\1\s\UI\Dialogs\ContentsTable\FolderDlg.cpp
Line 1357`

**Comment by stephenegriffin** [comment] 2023-11-14 15:13
Dupe of #49

**Closed by stephenegriffin** 2023-11-14 15:13 UTC
